### ISSUE TITLE
NuGet package for GitExtensions.Extensibility

### ISSUE THREAD

**Issue by maraf** [gitextensions/gitextensions.extensibility#13]
This package is a required dependency for all nuget-based GitExtensions plugins.

In the future, installing this package plugin developers should get all dependencies to extension points in GitExtensions. For the initial release, I think this package could be empty and developers will use standard MSBuild reference into downloaded portable GE.

**Comment by mast-eu** [comment]
Some questions come to my mind:

1) instead of being empty, couldn't the initial release directly contain the content from #11?

2) I remember that this package needs to exist, since other packages list it as a dependency and you wouldn't find them on nuget.org otherwise.
But: Does this metapackage itself need to exist _on nuget.org_ or could it be on _any public_ feed, like GH package registry?

**Comment by maraf** [comment]
@mast-eu 
1) I was thinking about two packages and this package has dependency on `Extensibility.Tools`. Opinions?
2) It may differ based on feed vendor. Myget doesn't need this package at all, Nuget requires it on its feed, GH who knows.

**Comment by mast-eu** [comment]
> 1. I was thinking about two packages and this package has dependency on `Extensibility.Tools`. Opinions?

Why 2 packages? One for the tools (PS scripts) and another one for the DLLs?
I see these as content of a single package since they are both "development resources" for plugin authors. In my head they will always be used conjointly. Do you have a use case where separation is needed?

> Nuget requires it on its feed

Hmm, I wanted to avoid the need for our org to publish on different feeds. Is there some documentation regarding this requirement?

**Comment by maraf** [comment]
> Why 2 packages? One for the tools (PS scripts) and another one for the DLLs?
> I see these as content of a single package since they are both "development resources" for plugin authors. In my head they will always be used conjointly. Do you have a use case where separation is needed?

GE itself will install this package as there will be shared contracts. I'm just copying pattern from [Microsoft.VisualStudio.SDK](https://www.nuget.org/packages/Microsoft.VisualStudio.SDK/) and [Microsoft.VSSDK.BuildTools](https://www.nuget.org/packages/Microsoft.VSSDK.BuildTools/). Maybe it's too complex for our use-case. It also depends on our version strategy. 

> Is there some documentation regarding this requirement?

I haven't found anything, just observed this behavior. It might be even more complicated with custom user feeds.

**Comment by mast-eu** [comment]
> GE itself will install this package as there will be shared contracts. I'm just copying pattern from [Microsoft.VisualStudio.SDK](https://www.nuget.org/packages/Microsoft.VisualStudio.SDK/) and [Microsoft.VSSDK.BuildTools](https://www.nuget.org/packages/Microsoft.VSSDK.BuildTools/). Maybe it's too complex for our use-case.

I still think it is more complex than needed. Maybe we can get a third opinion. Yes @RussKie, I'm looking at you :smirk: 



> > Is there some documentation regarding this requirement?
> 
> I haven't found anything, just observed this behavior. It might be even more complicated with custom user feeds.

The only relevant piece of documentation I found: https://docs.microsoft.com/en-us/nuget/reference/nuspec#dependencies-element

> `id` | (Required) The package ID of the dependency, such as "EntityFramework" and "NUnit", which is the **name of the package nuget.org shows** on a package page.

Not very explicit, but unfortunately it seems the package must actually be _on nuget.org_.

**Comment by RussKie** [comment]
My vision for this package was to rebrand `GitUIPluginInterfaces` into this, and move across any other shared general purpose functionality from `ResourceManager` and `GitExtUtils`.
This way both GE and plugins are developed against the same codebase.

With regards to mimic'ing big boys - I wouldn't do this now, we are not at the same level (just yet 😄). So I'd go for KISS.
My 5c

**Comment by maraf** [comment]
I'm the ultimate master of over complicated solutions, so...
Ok, I will update the #11 to be the main package.

One question: "Tools" package currently hooks to build events to automatically download portable archive, copy build output to portable instance, etc. How do you suggest to "turn these things off" when the package is installed to GE codebase?

**To makes things clear for me**: We will move sources of `GitUIPluginInterfaces` to the repository, produce nuget package and this package will be consumed by **both** plugins and GE, am I right?

**Comment by mast-eu** [comment]
> How do you suggest to "turn these things off" when the package is installed to GE codebase?

For the moment we might even ignore this aspect, since this package is not yet needed in GE main repo. Once it is needed, we might add some flag or simply check for the `SolutionName` macro.

> **To makes things clear for me**: We will move sources of `GitUIPluginInterfaces` to the repository, produce nuget package and this package will be consumed by **both** plugins and GE, am I right?

Yes, that's the idea.

**Comment by RussKie** [comment]
> I'm the ultimate master of over complicated solutions

😆 

> **To makes things clear for me**: We will move sources of `GitUIPluginInterfaces` to the repository, produce nuget package and this package will be consumed by **both** plugins and GE, am I right?

Yes

**Comment by mast-eu** [comment]
The package has been published: https://www.nuget.org/packages/GitExtensions.Extensibility/0.1.0.31

**Comment by RussKie** [comment]
🎉
