### ISSUE TITLE
Deprecate SetNameAndDescription()

### ISSUE THREAD

**Issue by mast-eu** [gitextensions/gitextensions.extensibility#14]
@RussKie raised an issue that the scope of the method `SetNameAndDescription(name)` in `GitPluginBase` is not very clear: https://github.com/gitextensions/gitextensions.plugintemplate/pull/1#discussion_r291406400.

I did some tests with the Statistics plugin to figure it out. I replaced `SetNameAndDescription("Statistics");` with 
```
Name = "Statistics (name)";
Description = "Statistics (description)";
```

_Description_ is a localized string that is used in both the plugins main menu and settings:

![image](https://user-images.githubusercontent.com/46861028/59100969-e3cb6b80-8927-11e9-83ce-2cf6574438fa.png)

![image](https://user-images.githubusercontent.com/46861028/59101657-f2b31d80-8929-11e9-9c2e-b97c9959cbd2.png)

_Name_ is used as prefix in `GitExtensions.settings`. This is not localized, so settings do not get lost when user switches language.

```
  <item>
    <key>
      <string>Statistics (name)Directories to ignore (EndsWith)</string>
    </key>
    <value>
      <string>\Debug;\Release;\obj;\bin</string>
    </value>
  </item>
```

Using the _Name_ as prefix already caused problems in the past and there's an open issue about this: https://github.com/gitextensions/gitextensions/issues/5797.

I think we should substitute _Name_ with a _GUID_ (as suggested in https://github.com/gitextensions/gitextensions/issues/5797) and rename  _Description_ to _Name_.

Afterwards, `SetNameAndDescription()` can be removed.

**Comment by ivangrek** [comment]
We could do it here 
https://github.com/gitextensions/gitextensions/pull/8574

**Comment by mast-eu** [comment]
> We could do it here
> [gitextensions/gitextensions#8574](https://github.com/gitextensions/gitextensions/pull/8574)

I agree.

**Comment by ivangrek** [comment]
Resolved: https://github.com/gitextensions/gitextensions/pull/8995
