### ISSUE TITLE
Add Bisect-Test scripts

### ISSUE THREAD

**Issue by BinHavin0323** [gitextensions/gitextensions.extensibility#25]
Add Bisect-Test scripts

Lets you run Bisect on Gitextensions project with automated builds and lets you know when ready to test.  Facilitates users doing actions in program to test.

Does the following:
- Cleans all files except this script in all submodules and this repo
 - Updates submodules
- Builds
- Runs built file
- Beeps to let you get a pot of coffee when build finishes
- Waits for program to exit
- Asks user if it did as expected

git bisect will auto mark good/bad/skip based on result and keep going

Example test in powershell
Example test in powershell
```ps
.\scripts\Run-BisectTest.ps1 -Bad master -Good v3.5.4 
#OR
.\scripts\Run-BisectTest.ps1 -Bad master -Good v3.5.4 -Force
```
Force will not ask user if they want to run destructive git cleans.

## Proposed changes

- Add bisect scripts to help track down where something broke in GE project

### Test methodology 

-  used in tracking down where #10242 was caused.

## Test environment(s) 

```ps
$PSVersionTable
```

```
Name                           Value
----                           -----
PSVersion                      7.2.6
PSEdition                      Core
GitCommitId                    7.2.6
OS                             Microsoft Windows 10.0.19044
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

## Merge strategy

I agree that the maintainer squash merge this PR (if the commit message is clear).

----

:black_nib: I contribute this code under [The Developer Certificate of Origin](../blob/master/contributors.txt).

__Originally posted by @vbjay in https://github.com/gitextensions/gitextensions/pull/10273__

**Comment by BinHavin0323** [comment]
- [ ] []()

**Comment by vbjay** [comment]
@BinHavin0323  please stop spamming these comments on our pull requests.

**Comment by vbjay** [comment]
![image](https://user-images.githubusercontent.com/3629489/196058891-02af8365-f256-4f99-8c4c-df2c15742390.png)
